# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# For Azure Linux 3.0 image, pass azurelinux as a value for NAMESPACE
ARG NAMESPACE=cbl-mariner

FROM mcr.microsoft.com/${NAMESPACE}/base/python:3 AS python-builder

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt --target=/app/python-packages

COPY . .

# Assuming this image name was used while creating the distroless python image using Marinara.
FROM distroless/python:3

WORKDIR /app

COPY --from=python-builder /app /app
COPY --from=python-builder /app/python-packages/ /usr/lib/python3.9/site-packages/

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

# HOST_PORT:        8000
# CONTAINER_PORT:   5000
