# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG AZL_VERSION=2.0
ARG NAMESPACE=cbl-mariner

FROM mcr.microsoft.com/$NAMESPACE/base/core:${AZL_VERSION} as installer

ARG AZL_VERSION=2.0

RUN tdnf install -y --releasever=${AZL_VERSION} shadow-utils python3 && tdnf clean all

COPY scripts/ /usr/sbin/

RUN chmod +x /usr/sbin/*

# Squash image layers into one layer.
FROM scratch

COPY --from=installer / /
CMD ["bash"]
