# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG NAMESPACE=cbl-mariner

FROM mcr.microsoft.com/${NAMESPACE}/base/nodejs:18 AS nodejs-builder

WORKDIR /app

COPY package.json .
COPY server.js .

RUN npm install

# Assuming this image name was used while creating the distroless nodejs image using Marinara.
FROM distroless/nodejs:18

WORKDIR /app

COPY --from=nodejs-builder /app /app

CMD [ "npm", "run", "start" ]

# HOST_PORT:        8080
# CONTAINER_PORT:   8080
