# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# For Azure Linux 3.0 image, pass azurelinux as a value for NAMESPACE
ARG NAMESPACE=cbl-mariner

FROM mcr.microsoft.com/${NAMESPACE}/base/rust:1 AS rust-builder

WORKDIR /usr/src/app

COPY azure-linux-rust-app/ .

RUN cargo install --path .

# Assuming this image name was used while creating the distroless cc image using Marinara.
FROM distroless/cc

WORKDIR /usr/src/app

COPY --from=rust-builder /usr/src/app /usr/src/app

CMD ["target/release/azure-linux-rust-app"]

# HOST_PORT:        8080
# CONTAINER_PORT:   8080
